[project]
name = "cÃ³digo"
version = "0.0.1"
description = "Primer Proyecto Diplomado"
authors = [
    {name = "Andres Perez",email = "jheissonperez@usantotomas.edu.co"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch (>=2.7.1,<3.0.0)",
    "pandas (>=2.3.0,<3.0.0)",
    "numpy (>=2.3.0,<3.0.0)",
    "seaborn (>=0.13.2,<0.14.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
